#!/usr/bin/env sh

userresources=${HOME}/.Xresources
usermodmap=${HOME}/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f "${sysresources}" ]; then
    xrdb -merge "${sysresources}"
fi

if [ -f "${sysmodmap}" ]; then
    xmodmap "${sysmodmap}"
fi

if [ -f "${userresources}" ]; then
    xrdb -merge "${userresources}"
fi

if [ -f "${usermodmap}" ]; then
    xmodmap "${usermodmap}"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for file in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        # shellcheck disable=SC1090
        [ -x "${file}" ] && . "${file}"
    done
    unset file
fi

# Set screen options
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrandr --dpi 96

# Change keyboard sensitivity to something sane (smooth)
xset r rate 300 50

# Set keybindings for extra keys
# shellcheck disable=SC2154
xbindkeys -f "${XDG_CONFIG_HOME}/X11/xbindkeysrc" &

# Launch cjk languages keyboard utility
fcitx5 -d &

# Start compositor
picom &

# Start notifictations daemon
dunst &

# Set wallpaper
"${HOME}"/.fehbg &

# Start window manager
"${XDG_CONFIG_HOME}/X11/xroot" &
exec dwm
